name: Run Vitest on PR

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Replace setup-node and the manual curl install with this
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        # You can specify a version if needed, e.g.:
        # with:
        #   bun-version: 1.1.10

      # This step will now work correctly
      - name: Install dependencies
        run: bun install

      - name: Run Vitest
        run: bun run test
